lib/listapp_web/router.ex
defmodule ListappWeb.Router do
  use ListappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ListappWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListappWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/design", PageController, :design

    resources "/events", EventController, only: [:show, :index] 
    # get "/events/:id", EventController, :show
    get "/items", ItemController, :live

    resources "/users", UserController, only: [:new, :create, :show]
    get "/login", SessionController, :new
    delete "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:create], singleton: true
  end


  scope "/manage", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/events", EventController do
      resources "/items", ItemController
      put "/items/:id/claim", ItemController, :claim
      resources "/guests", GuestController
      resources "/comments", CommentController
    end
  end

  scope "/admin", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/users", UserController, except: [:new, :create] 
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListappWeb do
  #   pipe_through :api
  # end

end

lib/listapp/events/guest.ex
defmodule Listapp.Events.Guest do
  use Ecto.Schema
  import Ecto.Changeset
  
  alias Listapp.Accounts.User
  alias Listapp.Events.Event

  schema "guests" do
    belongs_to :user, User
    belongs_to :event, Event
    # field :user_id, :id
    # field :event_id, :id

    timestamps()
  end

  @doc false
  def changeset(guest, attrs) do
    guest
    |> cast(attrs, [:user_id, :event_id])
    |> validate_required([])
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:event_id)
  end
end

lib/listapp_web/controllers/guest_controller.ex
defmodule ListappWeb.GuestController do
  use ListappWeb, :controller

  alias Listapp.Events
  alias Listapp.Events.Guest

  # def index(conn, _params) do
  #   guests = Events.list_guests()
  #   render(conn, "index.html", guests: guests)
  # end

  def new(conn, %{"event" => event}) do
    changeset = Events.change_guest(%Guest{})
    render(conn, "new.html", event: event, changeset: changeset)
  end

  def create(conn, %{"event_id" => event_id}) do
    event = Events.get_event!(event_id) 
    case Events.create_guest(conn.assigns.current_user, event) do
      {:ok, _guest} ->
        conn
        |> put_flash(:info, "Guest created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", event: event, changeset: changeset)
    end
  end

  # def show(conn, %{"id" => id}) do
  #   guest = Events.get_guest!(id)
  #   render(conn, "show.html", guest: guest)
  # end

  # def edit(conn, %{"id" => id}) do
  #   guest = Events.get_guest!(id)
  #   changeset = Events.change_guest(guest)
  #   render(conn, "edit.html", guest: guest, changeset: changeset)
  # end

  # def update(conn, %{"id" => id, "guest" => guest_params}) do
  #   guest = Events.get_guest!(id)

  #   case Events.update_guest(guest, guest_params) do
  #     {:ok, guest} ->
  #       conn
  #       |> put_flash(:info, "Guest updated successfully.")
  #       |> redirect(to: Routes.guest_path(conn, :show, guest))

  #     {:error, %Ecto.Changeset{} = changeset} ->
  #       render(conn, "edit.html", guest: guest, changeset: changeset)
  #   end
  # end

  def delete(conn, %{"event_id" => event_id, "id" => user_id}) do
    guest = Events.get_guest_by_user_and_event_id!(user_id, event_id)
    # event = Events.get_event!(event_id)
    
    # {:ok, _guest} = Events.delete_event_guest(event_id, user_id)
    {:ok, _guest} = Events.delete_guest(guest)

    conn
    |> put_flash(:info, "Guest removed successfully.")
    |> redirect(to: Routes.event_path(conn, :show, event_id))
  end
end

lib/listapp_web/views/guest_view.ex
defmodule ListappWeb.GuestView do
  use ListappWeb, :view
end

lib/listapp_web/templates/guest/edit.html.eex
<h1>Edit Guest</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.guest_path(@conn, :update, @guest)) %>

lib/listapp_web/templates/guest/form.html.eex
<%= form_for @changeset, @action, fn _f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div>
    <%= submit "RSVP" %>
  </div>
<% end %>

lib/listapp_web/templates/guest/index.html.eex
<h2>Who's Going</h2>  
<%= @event.host.name %>

<%= for user <- @guests do %>
  <div class="flex justify-between">
    <span><%= link user.name, to: Routes.user_path(@conn, :show, user) %></span>
    <%= if @event.host == @conn.assigns.current_user do %>
      <span><%= link "Remove", to: Routes.event_guest_path(@conn, :delete, @event.id, user), method: :delete, data: [confirm: "Are you sure?"] %></span>
    <% end %>
  </div>
<% end %>

<%# <div> %>
  <%# Share using this link: <%= share_link(@conn) %1> %>
  <%# </div> %>
<%= render ListappWeb.GuestView, "form.html", action: Routes.event_guest_path(@conn, :create, @event.id), event: @event, changeset: @changeset %>

lib/listapp_web/templates/guest/new.html.eex
<h1>New Guest</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_guest_path(@conn, :create, @event, @changeset)) %>


<%# <span><%= link "Back", to: Routes.guest_path(@conn, :index) %1></span> %>

lib/listapp_web/templates/guest/show.html.eex
<h1>Show Guest</h1>