lib/listapp_web/router.ex
defmodule ListappWeb.Router do
  use ListappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ListappWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListappWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/design", PageController, :design

    resources "/events", EventController, only: [:show, :index] 
    # get "/events/:id", EventController, :show
    get "/items", ItemController, :live

    resources "/users", UserController, only: [:new, :create, :show]
    get "/login", SessionController, :new
    delete "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:create], singleton: true
  end


  scope "/manage", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/events", EventController do
      resources "/items", ItemController
      put "/items/:id/claim", ItemController, :claim
      resources "/guests", GuestController
      resources "/comments", CommentController
    end
  end

  scope "/admin", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/users", UserController, except: [:new, :create] 
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListappWeb do
  #   pipe_through :api
  # end

end

lib/listapp_web/views/layout_view.ex
defmodule ListappWeb.LayoutView do
  use ListappWeb, :view
end

lib/listapp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Listapp · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body class="bg-gray-100">
    <header class="bg-teal-500 ">
      <nav class="container mx-auto flex items-center justify-between flex-wrap py-4 px-4">
        <%= link to: Routes.page_path(@conn, :index) do %>
        <div class="flex items-center flex-shrink-0 text-white mr-6">
          <span class="font-semibold text-xl tracking-tight">Dean's Event App</span>
        </div>
      <% end %>
        <div class="block lg:hidden collapsible">
          <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
          </button>
        </div>
        <div class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto">
          <div class="text-sm lg:flex-grow">
            <span class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white mr-4"><%= link "Events", to: Routes.event_path(@conn, :index) %></span>
            <span class="block mt-4 lg:inline-block lg:mt-0 text-teal-200 hover:text-white"><%= link "Users", to: Routes.user_path(@conn, :index) %></span>

          </div>
          <div class="text-teal-200 text-sm">
              <%= if @current_user do %>
                <span class="text-white px-4"><%= link @current_user.username, to: Routes.user_path(@conn, :show, @current_user) %></span>
                <span >
                  <%= link "Logout", to: Routes.session_path(@conn, :delete), method: "delete" %>
                </span>
              <% else %>
                <span class="inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0"><%= link "Register", to: Routes.user_path(@conn, :new) %></span>
                <span class="inline-block text-sm px-4 py-2 leading-none rounded text-white hover:border-transparent hover:text-teal-500 hover:bg-white mt-4 lg:mt-0"><%= link "Login", to: Routes.session_path(@conn, :new) %></span>
              <% end %>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container mx-auto py-4 px-4 ">
    <div class="alert alert-info hide" role="alert"><%= get_flash(@conn, :info) %></div>
    <p class="alert alert-danger hide" role="alert"><%= get_flash(@conn, :error) %></p>
    <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>