lib/listapp_web/router.ex
defmodule ListappWeb.Router do
  use ListappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ListappWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListappWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/design", PageController, :design

    resources "/events", EventController, only: [:show, :index] 
    # get "/events/:id", EventController, :show
    get "/items", ItemController, :live

    resources "/users", UserController, only: [:new, :create, :show]
    get "/login", SessionController, :new
    delete "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:create], singleton: true
  end


  scope "/manage", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/events", EventController do
      resources "/items", ItemController
      put "/items/:id/claim", ItemController, :claim
      resources "/guests", GuestController
      resources "/comments", CommentController
    end
  end

  scope "/admin", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/users", UserController, except: [:new, :create] 
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListappWeb do
  #   pipe_through :api
  # end

end

lib/listapp/events/comment.ex
defmodule Listapp.Events.Comment do
  use Ecto.Schema
  import Ecto.Changeset
  alias Listapp.Accounts.User
  alias Listapp.Events.Event

  schema "comments" do
    field :message, :string
    # field :user_id, :id
    # field :event_id, :id
    belongs_to :user, User
    belongs_to :event, Event

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:message])
    |> validate_required([:message])
  end
end

lib/listapp_web/controllers/comment_controller.ex
defmodule ListappWeb.CommentController do
  use ListappWeb, :controller

  alias Listapp.Events
  alias Listapp.Events.Comment

  plug :authorize_commenter when action in [:edit, :delete, :update]

  def index(conn, %{"event_id" => event_id}) do
    comments = Events.list_event_comments(event_id)
    render(conn, "index.html", comments: comments)
  end

  def new(conn, %{"event_id" => event_id}) do
    changeset = Events.change_comment(%Comment{})
    render(conn, "new.html", event_id: event_id, changeset: changeset)
  end

  def create(conn, %{"comment" => comment_params, "event_id" => event_id}) do
    event = Events.get_event!(event_id)
    case Events.create_comment(conn.assigns.current_user, event, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset, event_id: event_id)
    end
  end

  # def show(conn, %{"id" => id}) do
  #   comment = Events.get_comment!(id)
  #   render(conn, "show.html", comment: comment)
  # end

  def edit(conn, %{"id" => id, "event_id" => event_id}) do
    comment = Events.get_comment!(id)
    changeset = Events.change_comment(comment)
    render(conn, "edit.html", comment: comment, event_id: event_id, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params, "event_id" => event_id}) do
    comment = Events.get_comment!(id)
    event = Events.get_event!(event_id)
    case Events.update_comment(comment, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, event_id: event_id, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id, "event_id" => event_id}) do
    comment = Events.get_comment!(id)
    {:ok, _comment} = Events.delete_comment(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :show, event_id))
  end

  defp authorize_commenter(conn, _opts) do
    %{params: %{"id" => comment_id, "event_id" => event_id}} = conn
    comment = Events.get_comment!(comment_id)
    if conn.assigns.current_user == comment.user do
      conn
    else
      conn
      |> put_flash(:error, "You are not the owner of that comment.")
      |> redirect(to: Routes.event_path(conn, :show, event_id))
      |> halt()
    end
  end

end

lib/listapp_web/views/comment_view.ex
defmodule ListappWeb.CommentView do
  use ListappWeb, :view
  use Timex

  def format_timestamp(comment_timestamp) do
    case Timex.Format.DateTime.Formatters.Relative.format(comment_timestamp, "{relative}") do
      {:ok, timestamp} -> timestamp
      {:error, error} -> error
    end
  end

  def comment_owner?(conn, comment) do
    conn.assigns.current_user.id === comment.user.id
  end

  def is_edited?(comment) do
    comment.updated_at != comment.inserted_at
  end


end

lib/listapp_web/templates/comment/edit.html.eex
<h1>Edit Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_comment_path(@conn, :update, @event_id, @comment)) %>

lib/listapp_web/templates/comment/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="flex mb-4 mt-2">
    <%# <%= label f, :message %1> %>
    <%= text_input f, :message, placeholder: "Type your comment here..." %>
    <%= error_tag f, :message %>
    
    <div class="mx-4">
      <%= submit "Save" %>
    </div>
  </div>
<% end %>

lib/listapp_web/templates/comment/index.html.eex
<h2 class="">Comments</h2>
  <%= render ListappWeb.CommentView, "form.html", action: Routes.event_comment_path(@conn, :create, @event.id), changeset: @changeset %> 
  <%= render_many @event.comments, ListappWeb.CommentView, "show.html", conn: @conn%>

lib/listapp_web/templates/comment/new.html.eex
<h1>New Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_comment_path(@conn, :create, @event_id)) %>

lib/listapp_web/templates/comment/show.html.eex
<div class="flex mb-4 max-w-md ">
  <div class="left pr-3 py-1">
    <div class="profile-picture w-6">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M10 20a10 10 0 1 1 0-20 10 10 0 0 1 0 20zM7 6v2a3 3 0 1 0 6 0V6a3 3 0 1 0-6 0zm-3.65 8.44a8 8 0 0 0 13.3 0 15.94 15.94 0 0 0-13.3 0z"/></svg>
    </div>
  </div>
  <div class="right">
    <p class="comment">
    <span class="font-bold text-gray-900 mr-1">
      <%= link @comment.user.name, to: Routes.user_path(@conn, :show, @comment.user) %>
    </span>
    <span><%= @comment.message %></span>
    </p>
    <div class="flex justify-between">
      <div class="text-xs text-gray-700">
        <span ><%= format_timestamp(@comment.inserted_at) %></span>
        <%= if is_edited?(@comment) do %> 
          <span> - edited</span> 
        <% end %>
      </div>
      <div class="actions text-xs text-gray-700">
        <%= if comment_owner?(@conn, @comment) do %>
        <span><%= link "Edit", to: Routes.event_comment_path(@conn, :edit, @conn.assigns.event.id, @comment) %></span>
        <span><%= link "Delete", to: Routes.event_comment_path(@conn, :delete,  @conn.assigns.event.id, @comment), method: :delete, data: [confirm: "Are you sure?"] %></span>
        <% end %>
      </div>
    </div>
  </div>
</div>