lib/listapp_web/router.ex
defmodule ListappWeb.Router do
  use ListappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug ListappWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ListappWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/design", PageController, :design

    resources "/events", EventController, only: [:show, :index] 
    # get "/events/:id", EventController, :show
    get "/items", ItemController, :live

    resources "/users", UserController, only: [:new, :create, :show]
    get "/login", SessionController, :new
    delete "/logout", SessionController, :delete
    resources "/sessions", SessionController, only: [:create], singleton: true
  end


  scope "/manage", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/events", EventController do
      resources "/items", ItemController
      put "/items/:id/claim", ItemController, :claim
      resources "/guests", GuestController
      resources "/comments", CommentController
    end
  end

  scope "/admin", ListappWeb do
    pipe_through [:browser, :authenticate_user]

    resources "/users", UserController, except: [:new, :create] 
  end

  # Other scopes may use custom stacks.
  # scope "/api", ListappWeb do
  #   pipe_through :api
  # end

end

lib/listapp/events/item.ex
defmodule Listapp.Events.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias Listapp.Events.Event
  alias Listapp.Accounts.User

  schema "items" do
    field :name, :string

    belongs_to :event, Event
    belongs_to :user, User

    timestamps()
  end

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:name, :event_id, :user_id])
    |> validate_required([:name])
  end

  def assign_changeset(item, attrs) do
    item
    |> cast(attrs, [:user_id])
  end

end

lib/listapp/web/item.ex
defmodule Listapp.Web.Item do
  use Ecto.Schema
  import Ecto.Changeset
  alias Listapp.Web.Event

  schema "items" do
    field :name, :string
    belongs_to :event, Event

    timestamps()
  end

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, [:name])
    |> validate_required([:name])
  end
end

lib/listapp_web/controllers/item_controller.ex
defmodule ListappWeb.ItemController do
  use ListappWeb, :controller
  alias Phoenix.LiveView
  alias Listapp.Events

  def live(conn, _params) do
    LiveView.Controller.live_render(conn, ListappWeb.ItemsList, session: %{})
  end

  def index(conn, %{"event_id" => event_id}) do
    items = Events.list_items_in_event(event_id)
    render(conn, "index.html", items: items)
  end

  def create(conn, %{"item" => item_params, "event_id" => event_id} = _params) do
    event = Events.get_event!(event_id)

    case Events.create_item(conn.assigns.current_user, event, item_params) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Item created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event_id))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id, "event_id" => event_id}) do
    item = Events.get_item!(id)
    {:ok, _item} = Events.delete_item(item)

    conn
    |> put_flash(:info, "Item deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :show, event_id))
  end

  def show(conn, %{"id" => id}) do
    item = Events.get_item!(id)
    render(conn, "show.html", item: item)
  end

  def edit(conn, %{"id" => id, "event_id" => event_id}) do
    item = Events.get_item!(id)
    event = Events.get_event!(event_id)
    changeset = Events.change_item(item)
    render(conn, "edit.html", event: event, item: item, item_changeset: changeset)
  end

  def update(conn, %{"id" => id, "event_id" => event_id, "item" => item_params}) do
    item = Events.get_item!(id)
    event = Events.get_event!(event_id)

    case Events.update_item(item, item_params) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Item updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, item: item, item_changeset: changeset)
    end
  end

  def claim(conn, %{"id" => id, "event_id" => event_id}) do
    item = Events.get_item!(id)
    event = Events.get_event!(event_id)

    case Events.assign_item(item, conn.assigns.current_user) do
      {:ok, _item} ->
        conn
        |> put_flash(:info, "Item claimed successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = _changeset} ->
        conn
        |> put_flash(:error, "Cannot claim")
        # render(conn, "edit.html", item: item, changeset: changeset)
        |> redirect(to: Routes.event_path(conn, :show, event))
    end
  end

end

lib/listapp_web/views/item_view.ex
defmodule ListappWeb.ItemView do
  use ListappWeb, :view

  def user_select_options(users) do
    Enum.map(users, fn user -> {user.name, user.id} end) 
  end
end

lib/listapp_web/templates/item/add.html.eex
<%= form_for @item_changeset, @action, [class: "flex"], fn f -> %>
  <%= if @item_changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= text_input f, :name, placeholder: "New item" %>
  <%= error_tag f, :name %>
  
  <%= submit "Add", class: "px-4 py-2 border rounded"%>
<% end %>

lib/listapp_web/templates/item/edit.html.eex
<h1>Edit Item</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_item_path(@conn, :update, @event, @item)) %>

lib/listapp_web/templates/item/form.html.eex
<%= form_for @item_changeset, @action, fn f -> %>
  <%= if @item_changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  
  <%= label f, :name, "New Item" %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= submit "Add" %>
<% end %>

lib/listapp_web/templates/item/index.html.eex
<h2>Items</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for item <- @items do %>
      <tr>
        <td><%= item.name %></td>
        <td>
          <%= if item.user do %>
            <%= item.user.name %>
          <% end %>
        </td>
        <td>
          <%# <span><%= link "Show", to: Routes.event_item_path(@conn, :show, @conn.assigns.event.id, item) %1></span> %>
          <span><%= link "Edit", to: Routes.event_item_path(@conn, :edit, @conn.assigns.event.id, item) %></span>
          <span><%= link "Delete", to: Routes.event_item_path(@conn, :delete, @conn.assigns.event.id, item), method: :delete, data: [confirm: "Are you sure?"] %></span>
          <span><%= link "Claim", to: Routes.event_item_path(@conn, :claim, @conn.assigns.event.id, item), method: :put %></span>
          <%# <%= form_for @assign_changeset, @action, fn f -> %1> <%= submit "Claim" %1> <% end %1> %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# <span><%= link "New Event", to: Routes.event_path(@conn, :new) %1></span> %>

lib/listapp_web/templates/item/live.html.leex
<section>
  <%= form_for @changeset, "#", [phx_change: :validate, phx_submit: :save], fn f -> %> 
  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>
  <%= submit "Save" %>
<% end %>

<ul>
  <%= for item <- @items do %>
    <li><%= item.name %></li>
  <% end %>
</ul>
</section>

lib/listapp_web/templates/item/show.html.eex
<div class="flex justify-between">

  <div><%= @item.name %></div>
  <div>
    <%= if @item.user do %>
      <%= @item.user.name %>
    <% end %>
  </div>
  <div>
    <span><%= link "Edit", to: Routes.event_item_path(@conn, :edit, @conn.assigns.event.id, @item) %></span>
    <span><%= link "Delete", to: Routes.event_item_path(@conn, :delete, @conn.assigns.event.id, @item), method: :delete, data: [confirm: "Are you sure?"] %></span>
    <span><%= link "Claim", to: Routes.event_item_path(@conn, :claim, @conn.assigns.event.id, @item), method: :put %></span>

  </div>
</div>